export const APP_ROUTES = {
  dashboard: '/',
  arrivals: '/arrivals',
  arrivalsCreate: '/arrivals/create',
  arrivalDetails: '/arrivals/:arrivalId',
  arrivalEdit: '/arrivals/:arrivalId/edit',
  departures: '/departures',
  departuresCreate: '/departures/create',
  departureDetails: '/departures/:departureId',
  departureEdit: '/departures/:departureId/edit',
  drafts: '/drafts',
  draftsCreate: '/drafts/create',
  draftDetails: '/drafts/:draftId',
  draftEdit: '/drafts/:draftId/edit',
  buffer: '/buffer',
  stocks: '/stocks',
  stockDetails: '/stocks/:stockId',
  uiKit: '/ui-kit',
  devicePreview: '/device-preview',
  settings: '/settings',
  settingsProfile: '/settings/profile',
  settingsBackup: '/settings/backup',
  settingsAbout: '/settings/about',
} as const;
